on: push
name: Find flag references
jobs:
  find_flags:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 11 # This value must be set if the lookback configuration option is not disabled for find-code-references.
    - name: find_flags
      uses: launchdarkly/find-code-references@v7
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
        projKey: java
        debug: true
