# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PERSONAL: ${{ secrets.PERSONAL }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: loop
        run: |
           if ( grep -q account ./node_modules/all_projects )
           then
           echo "job2"
           fi
           #while read -r line ; do echo "ad $line"; done < ./all_projects
      - name: Setup everything
        run: |
          #gh auth login --with-token env.PERSONAL
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          # gh auth status
          gh run list --workflow=wf3.yml
          sleep 5
          
      #- name: run another another workflow
      #  run: |
      #    gh workflow enable wf3.yml
      #    gh workflow run wf3.yml --ref master -f stage=dev
      - name: trigger with workflow_call
        uses: aadiupa/StringMatch/.github/workflows/wf3.yml@master
        with:
          stage: dev
