# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

        # - name: Export deployment matrix 
        # id: export-deployment-matrix
        # run: |
        #  JSON="$(cat ./node_modules/all_projects)"
        #  JSON="${JSON//'%'/'%25'}"
        #  JSON="${JSON//$'\n'/'%0A'}"
        #  JSON="${JSON//$'\r'/'%0D'}"
        #  echo "::set-output name=deployment-matrix::$JSON"
        # - name: print above
        #  run: echo "${{ steps.export-deployment-matrix.outputs.deployment-matrix }}"
      - name: loop
        run: |
           if ( grep -q account ./node_modules/all_projects )
           then
           echo "job1"
           fi
           #while read -r line ; do echo "ad $line"; done < ./all_projects
           #
  job2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PERSONAL: ${{ secrets.PERSONAL }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: loop
        run: |
           if ( grep -q account ./node_modules/all_projects )
           then
           echo "job2"
           fi
           #while read -r line ; do echo "ad $line"; done < ./all_projects
      - name: run another workflow
        run: |
          #gh auth login --with-token env.PERSONAL
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh auth status
          gh workflow run wf3.yml --ref my-branch -f stage=dev 
