# This is a basic workflow to help you get started with Actions

name: Cut Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      stage:
        description: 'release version'
        required: true
        default: 'release-'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          depth: 100
      - name: Cut a release
        id: car
        run: git branch release-v ebf860ed70ce18f3610970697012435574e98b20
