# This is a basic workflow to help you get started with Actions

name: Cut Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      stage:
        description: 'stage [dev,prod]'
        required: true
        default: 'dev'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cut Release Branch
        id: crb
        uses: jessicalostinspace/cut-release-action@v1.0.0
        with:
          repository-url: 'https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git'
          branch-prefix: 'release-v'
          semantic-version: ${{ steps.bsv.outputs.bumped-semantic-version }}
