# This is a basic workflow to help you get started with Actions

name: Cut Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      stage:
        description: 'stage [dev,prod]'
        required: true
        default: 'dev'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
     - name: Get Last Branch and Semantic Version Containing String
       id: lrb
       uses: jessicalostinspace/github-action-get-regex-branch@v1.0.8
       with:
        regex-string: 'release-v'
        repository-url: 'https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git'
     - name: Bump Semantic Version
       id: bsv
       uses: jessicalostinspace/bump-semantic-version-action@v1.0.1
       with:
        semantic-version: ${{ steps.lrb.outputs.last-semver }}
        version-type: 'MINOR'
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Cut Release Branch
       id: crb
       uses: jessicalostinspace/cut-release-action@v1.0.0
       with:
          repository-url: 'https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git'
          branch-prefix: 'release-v'
          semantic-version: ${{ steps.bsv.outputs.bumped-semantic-version }}
