name: wf3

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'stage [dev,prod]'
        required: true
        default: 'dev'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-2
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - if: ${{ github.event.inputs.stage == 'dev' }} 
        name: AWS Scripts
        run: |
          aws ecr batch-delete-image --repository-name my-repository --image-ids imageTag=d96852af275d
      - name: AWS Scripts 2
        run: |
          MANIFEST=$(aws ecr batch-get-image --repository-name my-repository --image-ids imageTag=latest --output json | jq --raw-output '.images[0].imageManifest')
          aws ecr put-image --repository-name my-repository --image-tag "$(git rev-parse --short=12 HEAD)" --image-manifest "$MANIFEST"
          aws ecr describe-images --repository-name my-repository
      - name: get output
        run: 
          echo "${{ github.event.inputs.stage }}"
      - name: loop
        run: |
           if ( grep -q account ./node_modules/all_projects )
           then
           echo "wf3.yml"
           fi
           while read -r line ; do echo "ad $line"; done < ./all_projects
